export const LIST_LAUNCHPADS_REQUEST = 'LIST_LAUNCHPADS_REQUEST';
export const LIST_LAUNCHPADS_SUCCESS = 'LIST_LAUNCHPADS_SUCCESS';
export const LIST_LAUNCHPADS_FAILURE = 'LIST_LAUNCHPADS_FAILURE';

export const LIST_LAUNCHES_REQUEST = 'LIST_LAUNCHES_REQUEST';
export const LIST_LAUNCHES_SUCCESS = 'LIST_LAUNCHES_SUCCESS';
export const LIST_LAUNCHES_FAILURE = 'LIST_LAUNCHES_FAILURE';